name: Despliegue de staging a AWS

on:
  workflow_dispatch: {}

env:
  AWS_REGION: us-east-1
  ENV: staging

jobs:
  deploy-staging:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Login a AWS
        uses: aws-actions/configure-aws-credentials@v5
        with: 
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ env.AWS_REGION }}
      
      - name: Setup de Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: infra
        run: |
          terraform init -reconfigure \
            -backend-config="bucket=180358-stockwiz-backend" \
            -backend-config="key=staging/terraform.tfstate" \
            -backend-config="region=us-east-1"

      - name: Terraform Plan
        working-directory: infra
        run: terraform plan -var-file="envs/staging.tfvars"

      - name: Terraform Apply
        working-directory: infra
        run: terraform apply -var-file="envs/staging.tfvars" -auto-approve
      
      - name: Login a ECR
        run: |
          aws ecr get-login-password --region $AWS_REGION \
            | docker login --username AWS --password-stdin \
              "$(aws sts get-caller-identity --query 'Account' --output text).dkr.ecr.$AWS_REGION.amazonaws.com"

      - name: Pushear imagenes y reiniciar servicio
        run: |
          chmod +x deploy.sh
          ./deploy.sh staging

      - name: Fin
        run: echo "STAGING desplegado con exito!"