name: Workflow for merging staging to main

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]

jobs:
  banner:
    runs-on: ubuntu-latest
    steps:
      - run: echo "PR to MAIN"

  sonar:
    uses: ./.github/workflows/sonar.yml
    with:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  postman-tests:
    uses: ./.github/workflows/postman-tests.yml
    with:
      collection_path: postman/StockWiz.postman_collection.json
      environment_path: postman/StockWiz.postman_environment.json

# Jobs to add:
# build (para confirmar integridad)
# install aws cli
# deploy con terraform