name: Workflow for Feature branches to develop

on:
  pull_request:
    branches: [develop]
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  banner:
    runs-on: ubuntu-latest
    steps:
      - run: echo "PR to DEVELOP"

  sonar:
    uses: ./.github/workflows/sonar.yml
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  postman-tests:
    uses: ./.github/workflows/postman-tests.yml
    with:
      collection_path: postman/StockWiz.postman_collection.json
      environment_path: postman/StockWiz.postman_environment.json

  dev-deploy:
    uses: ./.github/workflows/deploy-dev.yml
    needs: [sonar, postman-tests]
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}